---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - service-account.yaml
 - service-account-token.secret.yaml
 - token-sync-sa.yaml
 - token-sync-role.yaml
 - token-sync-rolebinding.yaml
 - token-sync-job.yaml
 - auth-config.yaml
 - authorino.yaml
 - envoy-config.yaml
 - envoy-service.yaml
 - envoy.yaml
 - route.yaml
