---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - api-key-secret.yaml
 - auth-config.yaml
 - authorino.yaml
#  - envoy-auth.yaml
 - envoy-config.yaml
 - envoy-service.yaml
 - envoy.yaml
 - route.yaml
